### ISSUE TITLE
Some element are flickering on OSX

### ISSUE THREAD

**Issue by leupibr** [leupibr/BombDefusal#17]
Some of the elements of the bomb are flickering on OSX:
* Timer (only font)
* Strikes (only font)
* The whole charger module
* The shole simon says module
* The whole battery module

The box itself, the serial number and the other stuff of the timer module looks good so far.

**Comment by gillima** [comment]
Also reproducible on Windows7, ThinkPad P50 when undocked. In this case, the Intel graphic card is used instead of the NVidia...

**Comment by leupibr** [comment]
@gillima No more flickering 👍  Nice job 🥇
